Name:           ros-indigo-rqt-gui-cpp
Version:        0.2.14
Release:        1%{?dist}
Summary:        ROS rqt_gui_cpp package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rqt_gui_cpp
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-nodelet
Requires:       ros-indigo-qt-gui >= 0.2.22
Requires:       ros-indigo-qt-gui-cpp >= 0.2.22
Requires:       ros-indigo-roscpp
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-nodelet
BuildRequires:  ros-indigo-qt-gui >= 0.2.22
BuildRequires:  ros-indigo-qt-gui-cpp >= 0.2.22
BuildRequires:  ros-indigo-roscpp

%description
rqt_gui_cpp enables GUI plugins to use the C++ client library for ROS.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Dirk Thomas <dthomas@osrfoundation.org> - 0.2.14-1
- Autogenerated by Bloom

